language: node_js
git:
  depth: 10
node_js:
  - 6.0.0
  - 6.1.0
  - 6.2.0
  - 6.2.1
  - 6.2.2
  - 6.3.0
matrix:
  fast_finish: true
# before_deploy:
# deploy:
# after_deploy:
# after_script:
# script:
#   - npm test
#   - npm version patch

# before_install:
install:
  - npm install
  - npm prune
cache:
  directories:
    - node_modules

#script:
#before_script:
#after_script:

#after_success:
#after_failure:

deploy:
  provider: npm
  email: ivo.putzer@gmail.com
  api_key:
    secure: c/CFYaOUfAo0nrNdOaPSpTS+eUzaqUGeHQ+d5UKpBm0ZJWbFzAy5rmFcnA2V5CmrATvrl/k0xnFvQrzbZz5uy+tVHR91n1Pw5V4uhsJNkizCHQYj3VuDF/5QsDkw53v13UMU+nYTqjJjRRzfN9av6OlU5nW+rg7Ng69/z8fMR00EUoPZ+QdLdpTwvkeouIfuLIMhgNOCkWDRQBwLLe/RVYTpfuLi+fGCzKIKxbZziRxPuEfbOMCx2sFBf+uLDQzJG5jR3UGkPtY0DbfzD/GTaovX1kidbFRgpKBwuAhN5vil0bqDbPGzEjsRLb/uNa6xwoorP1zDp+aadPGh8Y8VS756SK88j4KWZRLwcPIwL5ZUtmuTpr1oYqi836FSL3Bnsq7Bb2tggc0RR+K+0W1h7/Vu4I0bQqiIKx5X9v/Rpa6cgvkACWcbYGwDudJRitMhxhxUkeKv+k2CQubOnFZWaeC+QNpbdOlf0o4g606YYz3FtKJW9z5jSK6nVzn59sn9OBMXrr83q94HdHIxq3Oh0dCH7h9vJS9Zzd/cTnL0xQ1SocSWuq04rwsIJdZgiCJkEyLhosEj/1c8kzsg4pFY+j9rdCrUvxTbRCUBtQ0UwGOdKx3Bw066ntwnj/1MOOp7m/OK/AI1nMgf4rsUf0BcZLi2biCN5SKdxAyos4BNwks=
  on:
    repo: TRAVIS_REPO_SLUG
    branch: master
before_deploy: bin/travis/before_deploy
after_deploy: bin/travis/after_deploy
